# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from . import tobii_remote_pb2 as tobii__remote__pb2


class TobiiRemoteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGazePosOnScreen = channel.unary_unary(
            "/TobiiRemote/GetGazePosOnScreen",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=tobii__remote__pb2.GazePosOnScreen.FromString,
        )
        self.GetEyeTrackerInfo = channel.unary_unary(
            "/TobiiRemote/GetEyeTrackerInfo",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=tobii__remote__pb2.EyeTrackerInfo.FromString,
        )


class TobiiRemoteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGazePosOnScreen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEyeTrackerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TobiiRemoteServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetGazePosOnScreen": grpc.unary_unary_rpc_method_handler(
            servicer.GetGazePosOnScreen,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=tobii__remote__pb2.GazePosOnScreen.SerializeToString,
        ),
        "GetEyeTrackerInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetEyeTrackerInfo,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=tobii__remote__pb2.EyeTrackerInfo.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "TobiiRemote", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class TobiiRemote(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGazePosOnScreen(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/TobiiRemote/GetGazePosOnScreen",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tobii__remote__pb2.GazePosOnScreen.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetEyeTrackerInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/TobiiRemote/GetEyeTrackerInfo",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tobii__remote__pb2.EyeTrackerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
